In [35]:
import numpy as np

In [243]:
def find_index(arr: np.ndarray, i) -> np.ndarray:
    index = i+1
    for elem in arr[i+1:, i]:
        if elem != 0:
            return index
        index += 1   

def swap_row(arr_: np.ndarray, i) -> np.ndarray:
    arr = arr_.copy()
    target_index = find_index(arr, i)
    arr[[i, target_index]] = arr[[target_index, i]]
    return arr

def gaus_elimination(arr_):
    arr = arr_.copy()
    i = 0
    # Percorrendo a diagonal principal
    while i < arr.shape[0]:
        
        ## cheagando se o elemento da diagonal principal é 0
        if arr[i][i] == 0:
            arr = swap_row(arr, i)
            continue
        
        k = i+1
        # Percorrendo os elementos abaixo do elemento da diagonal principal
        while k < arr.shape[0]:
            factor = arr[k][i] / arr[i][i]
            arr[k] -= factor * arr[i] 
            k += 1 
        i += 1
    return arr

In [244]:
linear_system = [
    [3, 2, -4, 3],
    [2, 3, 3, 15],
    [5, -3, 1 , 14]
]

In [245]:
arr = np.array(linear_system, dtype=float)

In [246]:
arr

array([[ 3.,  2., -4.,  3.],
       [ 2.,  3.,  3., 15.],
       [ 5., -3.,  1., 14.]])

In [247]:
gaus_elimination(arr)

[[ 3.  2. -4.  3.]
 [ 2.  3.  3. 15.]
 [ 5. -3.  1. 14.]]

                3.0
                2.0
            

0.6666666666666666

[ 2.          1.33333333 -2.66666667  2.        ]
[[ 3.          2.         -4.          3.        ]
 [ 0.          1.66666667  5.66666667 13.        ]
 [ 5.         -3.          1.         14.        ]]

                3.0
                5.0
            

1.6666666666666667

[ 5.          3.33333333 -6.66666667  5.        ]

[[ 3.          2.         -4.          3.        ]
 [ 0.          1.66666667  5.66666667 13.        ]
 [ 0.         -6.33333333  7.66666667  9.        ]]

                1.6666666666666667
                -6.333333333333334
            

-3.8000000000000003

[ -0.          -6.33333333 -21.53333333 -49.4       ]




array([[ 3.        ,  2.        , -4.        ,  3.        ],
       [ 0.        ,  1.66666667,  5.66666667, 13.        ],
       [ 0.        ,  0.        , 29.2       , 58.4       ]])

In [188]:
-1.5 * arr[1]

array([ -3. ,  -4.5,  -4.5, -22.5])

In [173]:
swap(arr, 0)

array([[ 5, -3,  1, 14],
       [ 0,  3,  3, 15],
       [ 3,  2, -4,  3]])

In [167]:
arr

array([[ 5, -3,  1, 14],
       [ 0,  3,  3, 15],
       [ 3,  2, -4,  3]])

In [152]:
find_index(arr, 0, 0)

2

In [160]:
arr[[0, 2]] = arr[[2, 0]]

In [161]:
arr

array([[ 5, -3,  1, 14],
       [ 0,  3,  3, 15],
       [ 3,  2, -4,  3]])

In [138]:
arr

array([[ 5, -3,  1, 14],
       [ 0,  3,  3, 15],
       [ 5, -3,  1, 14]])

In [76]:
i, j = 2, 2

In [77]:
arr[i+1:, j]

array([], dtype=int64)

In [53]:
arr

array([[ 3,  2, -4,  3],
       [ 2,  3,  3, 15],
       [ 5, -3,  1, 14]])

In [51]:
i = 0
while i < arr.shape[0]:
    print(f"main dg elem {i}: {arr[i][i]}")
    print(f"main dg lin {i}:")
    print(arr[i])
    print('sub lines: ')
    j = i + 1
    while j < arr.shape[0]:
        print(arr[j][i:])
        j += 1

    i += 1

main dg elem 0: 3
main dg lin 0:
[ 3  2 -4  3]
sub lines: 
[ 2  3  3 15]
[ 5 -3  1 14]
main dg elem 1: 3
main dg lin 1:
[ 2  3  3 15]
sub lines: 
[-3  1 14]
main dg elem 2: 1
main dg lin 2:
[ 5 -3  1 14]
sub lines: 


In [39]:
LinearSistem(linear_system)

[[ 3  2 -4  3]
 [ 2  3  3 15]
 [ 5 -3  1 14]]
