In [1]:
import numpy as np
import linear_system

2. Compare as soluções retornadas pelos três métodos acima (Eliminação de
Gauss, Jacobi e Gauss-Seidel) rodando-os para os sistemas lineares cujas
matrizes ampliadas são as seguintes (utilize e = 10−5 para os métodos de
Jacobi e Gauss-Seidel):

 $\begin{pmatrix}
   10 & 1 & 1 & 12 \\
   1 & 10 & 1 & 12 \\
   1 & 1 & 10 & 12 
\end{pmatrix}
$

In [6]:
A = np.array([
    [10, 1, 1, 12],
    [1, 10, 1, 12],
    [1, 1, 10, 12]
], dtype =float)

In [7]:
linear_system.gaus_elimination(A)

array([[10.        ,  1.        ,  1.        , 12.        ],
       [ 0.        ,  9.9       ,  0.9       , 10.8       ],
       [ 0.        ,  0.        ,  9.81818182,  9.81818182]])

In [8]:
A[:, :-1]

array([[10.,  1.,  1.],
       [ 1., 10.,  1.],
       [ 1.,  1., 10.]])

In [9]:
b = A[:, -1]
b

array([12., 12., 12.])

In [10]:
x = np.zeros_like(b)

In [11]:
linear_system.gauss_seidel(A[:, :-1], x, A[:, -1])

KeyboardInterrupt: 